(define (domain pr2-tamp)
  (:requirements :strips :equality)
  (:constants base left right head)
  (:predicates
    (Arm ?a)
    (Item ?o)
    (Loc ?l)

    (Pose ?o ?p)
    (BPose ?o ?bp ?l)
    (Grasp ?o ?g)
    (Traj ?a ?t)
    (BTraj ?t)
    (Kin ?a ?o ?p ?g ?q ?t)
    (BaseMotion ?q1 ?t ?q2)
    (Supported ?o ?p ?l)
    (Vis ?o ?bp ?bq ?hq ?ht)

    (AtPose ?o ?p)
    (AtGrasp ?a ?o ?g)
    (HandEmpty ?a)
    (BConf ?q)
    (AtBConf ?q)
    
    (On ?o ?l)
    (Holding ?a ?o)
    (Uncertain ?o)
  )
  (:functions
    (MoveCost ?q1 ?q2)
    (PickCost)
    (PlaceCost)
    (DetectCost ?o ?l)
  )

  (:action move_base
    :parameters (?q1 ?q2 ?t)
    :precondition (and (BaseMotion ?q1 ?t ?q2)
                       (AtBConf ?q1))
    :effect (and (AtBConf ?q2)
                 (not (AtBConf ?q1))
                 (increase (total-cost) (MoveCost ?q1 ?q2)))
  )

  (:action pick
    :parameters (?a ?o ?p ?g ?q ?t)
    :precondition (and (Arm ?a)
                       (Item ?o)
                       (not (Uncertain ?o))
                       (AtPose ?o ?p)
                       (Kin ?a ?o ?p ?g ?q ?t)
                       (HandEmpty ?a)
                       (AtBConf ?q))
    :effect (and (AtGrasp ?a ?o ?g)
                 (not (AtPose ?o ?p))
                 (not (HandEmpty ?a))
                 (increase (total-cost) (PickCost)))
  )

  (:action place
    :parameters (?a ?o ?p ?g ?q ?t)
    :precondition (and (Kin ?a ?o ?p ?g ?q ?t)
                       (AtGrasp ?a ?o ?g)
                       (AtBConf ?q))
    :effect (and (AtPose ?o ?p)
                 (HandEmpty ?a)
                 (not (AtGrasp ?a ?o ?g))
                 (increase (total-cost) (PlaceCost)))
  )

  (:action detect
    :parameters (?l ?o ?bp ?bq ?hq ?ht)
    :precondition (and (Item ?o) 
                       (Loc ?l)
                       (BPose ?o ?bp ?l)
                       (Vis ?o ?bp ?bq ?hq ?ht)
                       (AtBConf ?bq)
                       (Uncertain ?o))
    :effect (and (Supported ?o ?bp ?l)
                 (AtPose ?o ?bp)
                 (not (Uncertain ?o))
                 (increase (total-cost) (DetectCost ?o ?l)))
  )

  (:derived (On ?o ?l)
    (exists (?p) (and (Supported ?o ?p ?l)
                      (AtPose ?o ?p)))
  )

  (:derived (Holding ?a ?o)
    (exists (?g) (and (Arm ?a) (Grasp ?o ?g)
                      (AtGrasp ?a ?o ?g)))
  )
)